<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="LAPTOP-TI082SJI" failures="2" tests="27" name="Test" time="113.548" errors="0" timestamp="2025-03-26T11:54:29 IST">
  <testcase classname="tests.TC_NC_002" name="newCustomerAdding" time="2.613"/>
  <testcase classname="tests.TC_NC_003" name="newCustomerAdding" time="2.639"/>
  <testcase classname="tests.TC_NC_004" name="newCustomerAdding" time="1.719"/>
  <testcase classname="tests.TC_NC_001" name="newCustomerAdding" time="12.444">
    <failure type="java.lang.AssertionError" message="No success alert appeared. Possible form submission failure.">
      <![CDATA[java.lang.AssertionError: No success alert appeared. Possible form submission failure.
at tests.TC_NC_001.verifySuccessAlert(TC_NC_001.java:74)
at tests.TC_NC_001.newCustomerAdding(TC_NC_001.java:52)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 11 stack frames]]>
    </failure>
  </testcase> <!-- newCustomerAdding -->
  <testcase classname="tests.TC_NC_005" name="newCustomerAdding" time="1.051"/>
  <testcase classname="tests.TC_NC_006" name="newCustomerAdding" time="1.371"/>
  <testcase classname="tests.TC_NC_007" name="newCustomerAdding" time="0.34"/>
  <testcase classname="tests.TC_NC_008" name="newCustomerAdding" time="0.517"/>
  <testcase classname="tests.TC_NC_009" name="newCustomerAdding" time="0.63"/>
  <testcase classname="tests.TC_NC_011" name="newCustomerAdding" time="0.253"/>
  <testcase classname="tests.TC_NC_010" name="newCustomerAdding" time="0.784"/>
  <testcase classname="tests.TC_NC_012" name="newCustomerAdding" time="0.998"/>
  <testcase classname="tests.TC_NC_015" name="newCustomerAdding" time="0.662"/>
  <testcase classname="tests.TC_NC_014" name="newCustomerAdding" time="0.759"/>
  <testcase classname="tests.TC_NC_013" name="newCustomerAdding" time="0.849"/>
  <testcase classname="tests.TC_NC_016" name="newCustomerAdding" time="1.727"/>
  <testcase classname="tests.TC_NC_017" name="newCustomerAdding" time="1.71"/>
  <testcase classname="tests.TC_NC_018" name="newCustomerAdding" time="2.489"/>
  <testcase classname="tests.TC_NC_019" name="newCustomerAdding" time="0.305"/>
  <testcase classname="tests.TC_NC_021" name="newCustomerAdding" time="0.255"/>
  <testcase classname="tests.TC_NC_020" name="newCustomerAdding" time="0.763"/>
  <testcase classname="tests.TC_NC_022" name="newCustomerAdding" time="1.296"/>
  <testcase classname="tests.TC_NC_023" name="newCustomerAdding" time="0.355"/>
  <testcase classname="tests.TC_NC_024" name="newCustomerAdding" time="1.149"/>
  <testcase classname="tests.TC_NC_025" name="newCustomerAdding" time="0.918"/>
  <testcase classname="tests.TC_NC_026" name="newCustomerAdding" time="0.644"/>
  <testcase classname="tests.TC_NC_027" name="newCustomerAdding" time="0.971">
    <failure type="java.lang.AssertionError" message="Error message mismatch expected [Emal-ID must not be blank] but found [Email-ID must not be blank]">
      <![CDATA[java.lang.AssertionError: Error message mismatch expected [Emal-ID must not be blank] but found [Email-ID must not be blank]
at tests.TC_NC_027.newCustomerAdding(TC_NC_027.java:21)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- newCustomerAdding -->
  <testcase classname="tests.TC_NC_028" name="newCustomerAdding" time="0.0">
    <ignored/>
  </testcase> <!-- newCustomerAdding -->
</testsuite> <!-- Test -->
